#!/usr/bin/bash

# SPDX-FileCopyrightText: 2020 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

set -euo pipefail

node="/usr/bin/tezos-node"

if [[ ! -f "$DATA_DIR/identity.json" ]]; then
    "$node" identity generate --data-dir "$DATA_DIR"
fi
